### PR TITLE
Update glslang.

### PR DESCRIPTION
**Pull request by orbea**
This updates glslang to the current upstream master, this fixes a build issue with `clang-10.0.0` and ppsspp. Vulkan still seems to work for me with the SDL frontend.

### CODE REVIEW

**Comment by orbea** [comment]
@hrydgard When you have a chance I would appreciate if you can check this PR over. :)

**Comment by orbea** [comment]
@hrydgard When pulling the submodule in ppsspp it is still stuck on commit f9d08a25fbe17e0677a89d398f4d7f232339c3f9. Do you know how to update it in ppsspp?

**Comment by hrydgard** [comment]
Yeah, I'll make a pull request.

**Comment by hrydgard** [comment]
There's a lot of new files and things to change in the project files too, I'll sort it out tonight.

(if you wanna try, just cd ext/glslang, git checkout master, git pull --rebase)

**Comment by orbea** [comment]
I'm not really sure what needs to be changed in regards to the project files, it seems to build and work fine for me, but thanks for reminding me on how to update submodules!

**Comment by hrydgard** [comment]
It's probably just the Windows projects that need updating.

**Comment by orbea** [comment]
Okay, I can wait for when you have a chance. :)

**Comment by hrydgard** [comment]
So I updated, but not going so good - there's some kind of path issue: 
https://travis-ci.org/hrydgard/ppsspp/builds/657945677?utm_source=github_status&utm_medium=notification

Should be easy to fix though, had to fix the same thing for Windows.

**Pull request merged**
